#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jan 31 09:42:44 2022

@author: sundaresan.sridhar
"""
#FUNCTION TO COMPARE INDICA AND SXR INVERSION FROM TOMAS
import st40_sxr_inversion_plots as ss_plot
import pickle

pulseNo = 9229
optimized_plot = True
methods = ['tomo_1D','Indica']

pulseNos = [9408,9560,9229,9409,9411,9539,9537,9538,9184]

#BASE_DIRECTORY
if optimized_plot:
    directory_base = '/home/sundaresan.sridhar/Modules/sxr_inversion/shots_optimized_'
    save_directory = '/home/sundaresan.sridhar/Modules/sxr_inversion/shots_optimized_tomo_1D_Indica_comparison'
else:
    directory_base = '/home/sundaresan.sridha5r/Modules/sxr_inversion/shots_'
    save_directory = '/home/sundaresan.sridhar/Modules/sxr_inversion/shots__tomo_1D_Indica_comparison'

#SWEEP OF PULSENOS
for pulseNo in pulseNos:
    #LOADING THE RESULTS
    results = {}
    for method in methods:
        if optimized_plot:
            filename = directory_base+method+'/'+str(pulseNo)+'/optimize_plots/optimized_'+str(pulseNo)+'.p'
        with open(filename,'rb') as handle:
            results[method] = pickle.load(handle)
    #Z SHIFT PLOT
    ss_plot.plot_z_shifts(results[methods[0]],save_directory=save_directory,saveFig=True,results2=results[methods[1]],methods=methods)
