# .readthedocs.yml

version: 2

sphinx:
  configuration: doc/conf.py

python:
  version: 3.8
  install:
    - path: .
      method: pip
      extra_requirements:
        - docs
  system_packages: true
