
defaults:
  - model: xrcs
  - plasma: default
  - priors: default
  - optimisation: bo_default
  - reader: exp
  - writer: default

pulse: 11560
tstart: 0.05
tend: 0.10
dt: 0.01

writer:
  pulse_to_write: 43000000
  run_info: "Bayesian Optimisation test"
