
defaults:
  - model: xrcs
  - plasma: default
  - priors: default
  - optimisation: bo_default
  - reader: exp
  - writer: default

pulse: 11089
tstart: 0.05
tend: 0.010
dt: 0.01

writer:
  run: "RUN02B"
  run_info: "Bayesian Optimisation test"
  best: False
  plot: False
