
defaults:
  - model: pi
  - optimisation: emcee_test
  - plasma: default
  - priors: default
  - reader: mock
  - writer: test

diagnostics: [
  "cxff_pi",
 ]
quantities: [
  "cxff_pi.ti",
  ]

pulse: None
tstart: 0.05
tend: 0.06
dt: 0.01
