filter_coords:
  cxff_pi:
    ti: [ "channel", [ 4, 5 ] ]
    vtor: [ "channel", [ 4, 5 ] ]
  cxff_tws_c:
    ti: [ "channel", [ 0, 2 ] ]
    vtor: [ "channel", [ 0, 2 ] ]
  cxff_tws_b:
    ti: [ "channel", [ 1, 3 ] ]
    vtor: [ "channel", [ 1, 3 ] ]

filter_limits: {}
