COMPOSITION_SETTINGS = {
    11314: {
        "tstart": 0.05,
        "tend": 0.12,
        "dt": 0.01,
        "t":None,
        "prad_mult": 1,
        "const_zeff": False,
        "zeff_const":2.0,
        "imp_from_zeff": True,
        "main_ion": "h",
        "impurities": ("c", "ar", "mo"),
        "concentration": (0.03, 0.001, 0.0005),
        "zeff_rhop_lim": (0, 0.8),
        "prad_instr": "t1d_blom_xy1",
        "prad_mult": 1,
        "nplot":3,
    },
    11418: {
        "tstart": 0.07,
        "tend": 0.18,
        "dt": 0.01,
        "t":None,
        "prad_mult": 1,
        "const_zeff": True,
        "zeff_const":2.0,
        "imp_from_zeff": True,
        "main_ion": "h",
        "impurities": ("b", "ar"),
        "concentration": (0.03, 0.0001),
        "zeff_rhop_lim": (0.4, 0.8),
        "prad_instr": "t1d_blom_xy1",
        "nplot":3,
    },
    12201: {
        "tstart": 0.12,
        "tend": 0.15,
        "dt": 0.01,
        "t":None,
        "prad_mult": 1,
        "const_zeff": True,
        "zeff_const":2.0,
        "imp_from_zeff": True,
        "main_ion": "h",
        "impurities": ("b", "ar"),
        "concentration": (0.03, 0.001),
        "zeff_rhop_lim": (0.4, 0.8),
        "prad_instr": "t1d_blom_xy1",
        "nplot":1,
    },
    13136: {
        "tstart": 0.03,
        "tend": 0.1,
        "dt": 0.01,
        "t":None,
        "prad_mult": 1,
        "const_zeff": True,
        "zeff_const":2.0,
        "imp_from_zeff": True,
        "main_ion": "h",
        "impurities": ("b", "ar"),
        "concentration": (0.03, 0.001),
        "zeff_rhop_lim": (0.4, 0.8),
        "prad_instr": "t1d_blom_xy1",
        "nplot":1,
    },
    13565: {
        "tstart": 0.04,
        "tend": 0.2,
        "dt": 0.01,
        "t":[0.07, 0.1, 0.14, 0.19],
        "prad_mult": 1,
        "const_zeff": False,
        "zeff_const":1.6,
        "imp_from_zeff": True,
        "main_ion": "h",
        "impurities": ("b", "ar"),
        "concentration": (0.03, 0.000001),
        "zeff_rhop_lim": (0, 0.8),
        "prad_instr": "t1d_blom_xy1",
        "nplot":1,
    },
    13661: {
        "tstart": 0.08,
        "tend": 0.12,
        "dt": 0.01,
        "t":None,
        "prad_mult": 1,
        "const_zeff": True,
        "zeff_const":2.0,
        "imp_from_zeff": True,
        "main_ion": "h",
        "impurities": ("b", "ar"),
        "concentration": (0.03, 0.000001),
        "zeff_rhop_lim": (0.4, 0.8),
        "prad_instr": "t1d_blom_xy1",
        "nplot":1,
    },
    13906: {
        "tstart": 0.07,
        "tend": 0.1,
        "dt": 0.01,
        "t":None,
        "prad_mult": 1,
        "const_zeff": True,
        "zeff_const":2.0,
        "imp_from_zeff": True,
        "main_ion": "h",
        "impurities": ("b", "ar"),
        "concentration": (0.03, 0.000001),
        "zeff_rhop_lim": (0.4, 0.8),
        "prad_instr": "t1d_blom_xy1",
        "nplot":1,
    },
    13706: {
        "tstart": 0.05,
        "tend": 0.15,
        "dt": 0.01,
        "t":None,
        "prad_mult": 1,
        "const_zeff": True,
        "zeff_const":2.0,
        "imp_from_zeff": True,
        "main_ion": "h",
        "impurities": ("b", "ar"),
        "concentration": (0.03, 0.000001),
        "zeff_rhop_lim": (0.4, 0.8),
        "prad_instr": "t1d_blom_xy1",
        "nplot":1,
    },
    14470: {
        "tstart": 0.05,
        "tend": 0.15,
        "dt": 0.01,
        "t":None,
        "prad_mult": 1,
        "const_zeff": False,
        "zeff_const":2.0,
        "imp_from_zeff": True,
        "main_ion": "h",
        "impurities": ("b", "ar"),
        "concentration": (0.03, 0.000001),
        "zeff_rhop_lim": (0.4, 0.8),
        "prad_instr": "t1d_blom_xy1",
        "nplot":1,
    },
    14624: {
        "tstart": 0.05,
        "tend": 0.1,
        "dt": 0.01,
        "t":None,
        "prad_mult": 1,
        "const_zeff": True,
        "zeff_const":2.0,
        "imp_from_zeff": True,
        "main_ion": "h",
        "impurities": ("b", "o"),
        "concentration": (0.03, 0.001),
        "zeff_rhop_lim": (0.4, 0.8),
        "prad_instr": "t1d_blom_xy1",
        "nplot":1,
    },
}

