defaults:
  - equilibrium: efit

phantom: False
mock: False

ppts_modelling_number: 0
set_ts: True
apply_rshift: True
profile_params_to_update: {}

filter_coords:
  cxff_pi:
    ti: [ "channel", [ 3, 5 ] ]
    vtor: [ "channel", [ 3, 5 ] ]
  cxff_tws_c:
    ti: [ "channel", [ 1, 2 ] ]
    vtor: [ "channel", [ 1, 2 ] ]

filter_limits: {}
revisions: {}
