profilers:
  electron_temperature: "mono_spline"
  electron_density: "mono_spline"
  ion_temperature: "cubic_spline"
  neutral_density: "gauss"
  impurity_density:ar: "gauss"
  impurity_density:c: "gauss"
  impurity_density:he: "gauss"
  toroidal_rotation: "gauss"

params:
  electron_density:
    xknots: [0.00, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.8, 0.875, 0.925, 0.95, 0.975, 0.99, 1.0, 1.025, 1.035, 1.05, 1.075, 1.085, 1.1]
    y0: 5.0e+19
    y1: 4.125e+19
    y2: 3.3e+19
    y3: 2.55e+19
    y4: 1.9e+19
    y5: 1.3125e+19
    y6: 8.75e+18
    y7: 7.0e+18
    y8: 5.125e+18
    y9: 4.2e+18
    y10: 3.3e+18
    y11: 2.6e+18
    y12: 2.0e+18
    y13: 1.7e+18
    y14: 1.3e+18
    y15: 9.0e+17
    y16: 6.5e+17
    y17: 4.0e+17
    y18: 2.0e+17
    y19: 0
  electron_temperature:
    xknots: [0.00, 0.125, 0.25, 0.375, 0.5, 0.625, 0.75, 0.8, 0.875, 0.925, 0.95, 0.975, 0.99, 1.0, 1.025, 1.035, 1.05, 1.075, 1.085, 1.1]
    y0: 2000
    y1: 1812.5
    y2: 1575
    y3: 1262.5
    y4: 975
    y5: 696.25
    y6: 427.5
    y7: 320
    y8: 200
    y9: 140
    y10: 110
    y11: 75
    y12: 60
    y13: 50
    y14: 38
    y15: 28
    y16: 20
    y17: 12
    y18: 6
    y19: 0

  ion_temperature:
    xknots: [0.00, 0.2, 0.4, 0.6, 0.8, 1.0]
    y0: 5.0e+3
    shape1: 0.9 # 0.7-1.05
    shape2: 0.8 # 0.5-0.9
    shape3: 0.6 # 0.5-0.9
    shape4: 0.5 # 0.5-0.9
    y1: 100

  neutral_density:
    y0: 1.0e+13
    y1: 5.0e+15
    yend: 5.0e+15
    wcenter: 0.01
    wped: 18
    peaking: 1

  impurity_density:ar:
    y0: 1.0e+17
    y1: 1.0e+15
    yend: 1.0e+15
    wcenter: 0.3
    wped: 3
    peaking: 2
  impurity_density:c:
    y0: 5.0e+17
    y1: 2.0e+17
    yend: 2.0e+17
    wcenter: 0.3
    wped: 3
    peaking: 2
  impurity_density:he:
    y0: 5.0e+17
    y1: 2.0e+17
    yend: 2.0e+17
    wcenter: 0.3
    wped: 3
    peaking: 2

  toroidal_rotation:
    y0: 500.0e+3
    y1: 1.0e+3
    yend: 1.0e+3
    peaking: 0.4
    wcenter: 2
    wped: 3
