
profilers:
  electron_temperature: "gauss"
  electron_density: "gauss"
  ion_temperature: "cubic_spline"
  neutral_density: "gauss"
  impurity_density:ar: "gauss"
  impurity_density:c: "gauss"
  impurity_density:he: "gauss"
  toroidal_rotation: "gauss"

params:
  electron_density:
    y0: 5.0e+19
    y1: 2.0e+18
    yend: 2.0e+18
    wped: 3
    wcenter: 0.3
    peaking: 1.2
  electron_temperature:
    y0: 2000
    y1: 100
    yend: 100
    wcenter: 0.2
    wped: 3
    peaking: 2

  ion_temperature:
    xknots: [ 0.00, 0.2, 0.4, 0.6, 0.8, 1.0, ]
    y0: 5.0e+3
    shape1: 0.9 # 0.7-1.05
    shape2: 0.8 # 0.5-0.9
    shape3: 0.6 # 0.5-0.9
    shape4: 0.5 # 0.5-0.9
    y1: 100

  neutral_density:
    y0: 1.0e+13
    y1: 5.0e+15
    yend: 5.0e+15
    wcenter: 0.01
    wped: 18
    peaking: 1

  impurity_density:ar:
    y0: 1.0e+17
    y1: 1.0e+15
    yend: 1.0e+15
    wcenter: 0.3
    wped: 3
    peaking: 2
  impurity_density:c:
    y0: 5.0e+17
    y1: 2.0e+17
    yend: 2.0e+17
    wcenter: 0.3
    wped: 3
    peaking: 2
  impurity_density:he:
    y0: 5.0e+17
    y1: 2.0e+17
    yend: 2.0e+17
    wcenter: 0.3
    wped: 3
    peaking: 2

  toroidal_rotation:
    y0: 500.0e+3
    y1: 1.0e+3
    yend: 1.0e+3
    peaking: 0.4
    wcenter: 2
    wped: 3
