method: "emcee"

param_names: ["impurity_density:ar.y0", "impurity_density:ar.peaking"
]
pca_profiles: ["ion_temperature", ]
pca_components: 3

starting_samples: 200
iterations: 1000
nwalkers: 40
stopping_criteria_factor: 0.005
sample_method: "high_density"
stopping_criteria: "mode"
burn_frac: 0.20
