ADF15 = {
    "he": {
        "1": dict(
            file_type="bnd",
            year="96",
        ),
    },
    "ne": {str(charge): dict(file_type="pju", year="96") for charge in range(0, 8)},
    "c": {str(charge): dict(file_type="bnd", year="96") for charge in range(5, 6)},
    "ar": {
        str(charge): dict(file_type="llu", year="transport") for charge in range(16, 18)
    },
}

ADF11: dict = {
    "h": {
        "scd": "96",
        "acd": "96",
        "ccd": "96",
        "plt": "96",
        "prb": "96",
        "prc": "96",
        "pls": "15",
        "prs": "15",
    },
    "he": {
        "scd": "89",
        "acd": "89",
        "ccd": "89",
        "plt": "89",
        "prb": "89",
        "prc": "89",
        "pls": "15",
        "prs": "15",
    },
    "li": {
        "scd": "96",
        "acd": "96",
        "ccd": "89",
        "plt": "96",
        "prb": "96",
        "prc": "89",
        "pls": "15",
        "prs": "15",
    },
    "be": {
        "scd": "89",
        "acd": "89",
        "ccd": "89",
        "plt": "89",
        "prb": "89",
        "prc": "89",
        "pls": "15",
        "prs": "15",
    },
    "b": {
        "scd": "89",
        "acd": "89",
        "ccd": "89",
        "plt": "89",
        "prb": "89",
        "prc": "89",
        "pls": "15",
        "prs": "15",
    },
    "c": {
        "scd": "89",
        "acd": "89",
        "ccd": "89",
        "plt": "89",
        "prb": "89",
        "prc": "89",
        "pls": "15",
        "prs": "15",
    },
    "ne": {
        "scd": "89",
        "acd": "89",
        "ccd": "89",
        "plt": "89",
        "prb": "89",
        "prc": "89",
        "pls": "15",
        "prs": "15",
    },
    "ar": {
        "scd": "89",
        "acd": "89",
        "ccd": "89",
        "plt": "42",
        "prb": "89",
        "prc": "89",
        "pls": "15",
        "prs": "15",
    },
    "ni": {
        "scd": "89",
        "acd": "89",
        "ccd": "89",
        "plt": "89",
        "prb": "89",
        "prc": "89",
        "pls": "15",
        "prs": "15",
    },
    "kr": {
        "scd": "89",
        "acd": "89",
        "ccd": "89",
        "plt": "42",
        "prb": "89",
        "prc": "89",
        "pls": "15",
        "prs": "15",
    },
    "xe": {
        "scd": "89",
        "acd": "89",
        "ccd": "89",
        "plt": "42",
        "prb": "89",
        "prc": "89",
        "pls": "15",
        "prs": "15",
    },
    "mo": {
        "scd": "89",
        "acd": "89",
        "ccd": "89",
        "plt": "89",
        "prb": "89",
        "prc": "89",
    },
    "w": {
        "scd": "89",
        "acd": "89",
        "ccd": "89",
        "plt": "42",
        "prb": "89",
        "prc": "89",
        "pls": "15",
        "prs": "15",
    },
}
