from indica.configs.readers.machineconf import MachineConf

# TODO: add "server" and "tree" information to this config and out of MDSUtils.
#      Reader anyway takes config as input to init!


class ST40Conf(MachineConf):
    def __init__(self):
        self.MACHINE_DIMS = ((0.15, 0.85), (-0.8, 0.8))
        self.INSTRUMENT_METHODS = {
            "efit": "equilibrium",
            "xrcs": "helike_spectroscopy",
            "pi": "spectrometer",
            "tws_c": "spectrometer",
            "cxff_pi": "charge_exchange",
            "cxff_tws_c": "charge_exchange",
            "cxff_tws_b": "charge_exchange",
            "cxqf_tws_c": "charge_exchange",
            "lines": "diode_filters",
            "smmh": "interferometry",
            "nirh": "interferometry",
            "ts": "thomson_scattering",
            "sxr_spd": "radiation",
            "sxrc_xy1": "radiation",
            "sxrc_xy2": "radiation",
            "sxrc_rz1": "radiation",
            "sxrc_rz2": "radiation",
            "blom_xy1": "radiation",
            "blom_rz1": "radiation",
            "blom_dv1": "radiation",
            "t1d_sxrc_xy1": "radiation_inversion",
            "t2d_sxrc_xy1": "radiation_inversion",
            "t1d_sxrc_xy2": "radiation_inversion",
            "t2d_sxrc_xy2": "radiation_inversion",
            "t1d_sxrc_rz1": "radiation_inversion",
            "t1d_sxrc_rz2": "radiation_inversion",
            "t1d_blom_xy1": "radiation_inversion",
            "t2d_blom_xy1": "radiation_inversion",
            "t1d_blom_rz1": "radiation_inversion",
            "ppts": "profile_fits",
            "bda": "profile_fits",
            "zeff_brems": "zeff",
            "transp_test": "transp",
            "astra": "astra",
            "metis": "metis",
            "solps": "solps",
        }
        self.QUANTITIES_PATH = {
            "equilibrium": {
                "t": ":time",
                "xpsin": ".profiles.psi_norm:xpsn",
                "R": ".psi2d:rgrid",
                "z": ".psi2d:zgrid",
                "f": ".profiles.psi_norm:f",
                "psi_axis": ".global:faxs",
                "psi_boundary": ".global:fbnd",
                "ftor": ".profiles.psi_norm:ftor",
                "rmji": ".profiles.psi_norm:rmji",
                "rmjo": ".profiles.psi_norm:rmjo",
                "psi": ".psi2d:psi",
                "vjac": ".profiles.psi_norm:vjac",
                "ajac": ".profiles.psi_norm:ajac",
                "rmag": ".global:rmag",
                "rgeo": ".global:rgeo",
                "rbnd": ".p_boundary:rbnd",
                "zmag": ".global:zmag",
                "zbnd": ".p_boundary:zbnd",
                "ipla": ".constraints.ip:cvalue",
                "wp": ".virial:wp",
                "df": ".constraints.df:cvalue",
                "data_q": ".data_q.score_1d",
            },
            "helike_spectroscopy": {
                "t": ":time",
                "wavelength": ":wavelen",
                "location": ".geometry:location",
                "direction": ".geometry:direction",
                "ti_w": ".global:ti_w",
                "ti_z": ".global:ti_z",
                "te_n3w": ".global:te_n3w",
                "te_kw": ".global:te_kw",
                "spectra_raw": ":intens",
                "spectra": ":spec_rad",
                "int_w": ".global:int_w",
                "int_k": ".global:int_k",
                "int_tot": ".global:int_tot",
                "int_n3": ".global:int_n3",
                "background": ".global:back_avg",
                "data_q": ".data_q.score_1d",
            },
            "interferometry": {
                "t": ":time",
                "location": ".geometry:location",
                "direction": ".geometry:direction",
                "ne_int": ".global:ne_int",
                "data_q": ".data_q.score_1d",
            },
            "diode_filters": {
                "t": ":time",
                "label": ":label",
                "location": ".geometry:location",
                "direction": ".geometry:direction",
                "brightness": ":data",
                "data_q": ".data_q.score_1d",
            },
            "radiation": {
                "t": ":time",
                "bad_channel": ":bad_channels",
                "location": ".geometry:location",
                "direction": ".geometry:direction",
                "brightness": ".profiles:emission",
                "data_q": ".data_q.score_1d",
            },
            "radiation_inversion": {
                "t": ":time",
                "channel": ":label",
                "prad": ".global:prad",
                "rhop": ".profiles.psi_norm:rhop",
                "R": ".profiles.rz_2d:r",
                "z": ".profiles.rz_2d:z",
                "emission_rhop": ".profiles.psi_norm:emis_loc",
                "emission_rz": ".profiles.rz_2d:emis_loc",
                "data_q": ".data_q.score_1d",
            },
            "charge_exchange": {
                "t": ":time",
                "wavelength": ":wavelen",
                "x": ":x",
                "y": ":y",
                "z": ":z",
                "R": ":R",
                "int": ".profiles:int",
                "ti": ".profiles:ti",
                "vtor": ".profiles:vtor",
                "spectra": ":spectra",
                "fit": ":full_fit",
                "data_q": ".data_q.score_1d",
            },
            "spectrometer": {
                "t": ":time",
                "location": ".geometry:location",
                "direction": ".geometry:direction",
                "wavelength": ":wavelen",
                "spectra": ":emission",
                "spectra_raw": ":intens",
                "data_q": ".data_q.score_1d",
            },
            "thomson_scattering": {
                "t": ":time",
                "x": ":x",
                "y": ":y",
                "z": ":z",
                "R": ":R",
                "ne": ".profiles:ne",
                "te": ".profiles:te",
                "pe": ".profiles:pe",
                "chi2": ".profiles:chi2",
                "data_q": ".data_q.score_1d",
            },
            "profile_fits": {
                "t": ":time",
                "rhop": ".profiles.psi_norm:rhop",
                "R": ".profiles.r_midplane:rpos",
                "z": ".profiles.r_midplane:zpos",
                "rhop_data": ".profiles.inputs:rhop",
                "R_data": ".profiles.inputs:rpos",
                "z_data": ".profiles.inputs:zpos",
                "ne_rhop": ".profiles.psi_norm:ne",
                "te_rhop": ".profiles.psi_norm:te",
                "pe_rhop": ".profiles.psi_norm:pe",
                "ti_rhop": ".profiles.psi_norm:ti",
                "vtor_rhop": ".profiles.psi_norm:vtor",
                "ne_R": ".profiles.r_midplane:ne",
                "te_R": ".profiles.r_midplane:te",
                "pe_R": ".profiles.r_midplane:pe",
                "ne_data": ".profiles.inputs:ne",
                "te_data": ".profiles.inputs:te",
                "pe_data": ".profiles.inputs:pe",
                "R_shift": ".global:rshift",
                "data_q": ".data_q.score_1d",
            },
            "zeff": {
                "t": ":time",
                "channel": ".diag_data.pi:label",
                "rhop": ".profiles.psi_norm:rhop",
                "R_shift": ".global:rshift",
                "bremss_avrg": ".global:brems",
                "bremss_hi": ".global:brems_hi",
                "bremss_low": ".global:brems_low",
                "zeff_avrg": ".global:zeff",
                "zeff_hi": ".global:zeff_hi",
                "zeff_low": ".global:zeff_low",
                "brightness": ".diag_data.pi:emis_int",
                "zeff": ".profiles.psi_norm:zeff",
                "bremss_emission": ".profiles.psi_norm:emis_loc",
                "te": ".profiles.psi_norm:te",
                "ne": ".profiles.psi_norm:ne",
                "data_q": ".data_q.score_1d",
            },
            "astra": {
                "t": ":time",
                "psi_axis": ".global:faxs",
                "psi_boundary": ".global:fbnd",
                "rmag": ".global:rmag",
                "rgeo": ".global:rgeo",
                "zmag": ".global:zmag",
                "zgeo": ".global:zgeo",
                "ipla": ".global:ipl",
                "wp": ".global:wth",
                "xpsin": ".profiles.psi_norm:xpsn",
                "f": ".profiles.psi_norm:fpol",
                "ftor": ".profiles.psi_norm:ftor",
                "rmji": ".profiles.psi_norm:rmji",
                "rmjo": ".profiles.psi_norm:rmjo",
                "rbnd": ".p_boundary:rbnd",
                "zbnd": ".p_boundary:zbnd",
                "df": ".constraints.df:cvalue",
                "vloop": ".global:upl",
                "psin": ".profiles.astra:psin",
                "rhot": ".profiles.astra:rho",
                "area": ".profiles.psi_norm:areat",
                "volume": ".profiles.psi_norm:volume",
                "te": ".profiles.astra:te",
                "ne": ".profiles.astra:ne",
                "ti": ".profiles.astra:ti",
                "omegator": ".profiles.astra:omega_tor",
                "vtor": ".profiles.astra:vtor",
                "R": ".psi2d:rgrid",
                "z": ".psi2d:zgrid",
                "psi": ".psi2d:psi",
            },
            "transp": {
                # "xpsin": ".profiles.psi_norm:xpsn", # Missing Equilibrium quantities
                # "R": ".psi2d:rgrid",
                # "z": ".psi2d:zgrid",
                # "f": ".profiles.psi_norm:f",
                # "ftor": ".profiles.psi_norm:ftor",
                # "rmji": ".profiles.psi_norm:rmji",
                # "rmjo": ".profiles.psi_norm:rmjo",
                # "psi": ".psi2d:psi",
                # "vjac": ".profiles.psi_norm:vjac",
                # "ajac": ".profiles.psi_norm:ajac",
                # "wp": ".virial:wp",
                # "df": ".constraints.df:cvalue",
                "t": ":time",
                "psi_boundary": ".global:fbnd",
                "psi_axis": ".global:faxs",
                "rmag": ".global:rmag",
                "zmag": ".global:zmag",
                "rgeo": ".global:rgeo",
                "zgeo": ".global:zgeo",
                "ipla": ".global:ip",
                "vloop": ".global:vloop",
                "rbnd": ".p_boundary:rbnd",
                "zbnd": ".p_boundary:zbnd",
                "psin": ".profiles.rhotor:psin",
                "rhot": ".profiles.rhotor:rhotor",
                "rhop": ".profiles.rhotor:rhopol",
                "te": ".profiles.rhotor:te",
                "ne": ".profiles.rhotor:ne",
                "ti": ".profiles.rhotor:ti",
                "omegator": ".profiles.rhotor:omega_tor",
                "vtor": ".profiles.rhotor:vtor",
            },
            "metis": {
                # "xpsin": ".profiles.psi_norm:xpsn", # Missing Equilibrium quantities
                # "R": ".psi2d:rgrid",
                # "z": ".psi2d:zgrid",
                # "f": ".profiles.psi_norm:f",
                # "psi_axis": ".global:faxs",
                # "psi_boundary": ".global:fbnd",
                # "ftor": ".profiles.psi_norm:ftor",
                # "rmji": ".profiles.psi_norm:rmji",
                # "rmjo": ".profiles.psi_norm:rmjo",
                # "psi": ".psi2d:psi",
                # "vjac": ".profiles.psi_norm:vjac",
                # "ajac": ".profiles.psi_norm:ajac",
                # "wp": ".virial:wp",
                # "df": ".constraints.df:cvalue",
                "t": ":time",
                "rmag": ".global:rmag",
                "zmag": ".global:zmag",
                "rgeo": ".global:rgeo",
                "zgeo": ".global:zgeo",
                "ipla": ".global:ip",
                "vloop": ".global:vloop",
                "rbnd": ".p_boundary:rbnd",
                "zbnd": ".p_boundary:zbnd",
                "psin": ".profiles.rho:psin",
                "rhot": ".profiles.rho:rhotor",
                "te": ".profiles.rho:te",
                "ne": ".profiles.rho:ne",
                "ti": ".profiles.rho:ti",
                "omegator": ".profiles.rho:omega_tor",
                "vtor": ".profiles.rho:vtor",
            },
        }
