method: "bo"

n_calls: 6
n_initial_points: 5
noise: 1.0E-10
acq_func: "LCB"
xi: 0.20
kappa: 2
initial_point_generator: "lhs"
use_previous_best: False

boundary_samples: 2000
model_samples: 10
posterior_samples: 1000
